# NumPy Opdrachten

In dit notebook vind je de volgende opdrachten:


- <a href="#np_opdracht1"> Opdracht 1</a> Maak deze opdracht ter voorbereiding op het college over NumPy.
- <a href="#np_opdracht2"> Opdracht 2</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht3"> Opdracht 3</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht4"> Opdracht 4</a> Deze opdracht is facultatief, voor als je meer uitdaging wilt.

<a id="np_opdracht1"></a>
## Opdracht 1 
**Maak deze opdracht ter voorbereiding op het college**

In [34]:
import numpy as np

- Maak een 1D array x aan met de cijfers 0 t/m 5

In [35]:
x = np.array([0, 1, 2, 3, 4, 5])
print(x)

# or
y = np.arange(0, 6)
print(y)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


- Laat de vorm (grootte van de dimensies) van de array zien

In [36]:
print(x.shape)

# or
print(x.ndim)

(6,)
1


- Hervorm de array x tot een 2D array (2, 3) 

In [37]:
x = x.reshape(2, 3)
print(x)

[[0 1 2]
 [3 4 5]]


- Wat is nu de vorm?


In [38]:
x.shape

(2, 3)

- Laat het datatype zien


In [39]:
x.dtype

dtype('int64')

- Sla een kopie van de array op in y


In [40]:
y = x.copy()
print(y)

[[0 1 2]
 [3 4 5]]


- Maak een transpose van x



In [41]:
x_transpose = np.transpose(x)
print(x_transpose)

[[0 3]
 [1 4]
 [2 5]]


- Maak een transpose van y


In [42]:
y_transpose = np.transpose(y)
print(y_transpose)

[[0 3]
 [1 4]
 [2 5]]


- Vermenigvuldig alle waarden van y met 2


In [43]:
y = y*2
print(y)

[[ 0  2  4]
 [ 6  8 10]]


- Concateneer de twee arrays in een nieuwe array `z`


In [44]:
z = np.concatenate([x, y])
print(z)

[[ 0  1  2]
 [ 3  4  5]
 [ 0  2  4]
 [ 6  8 10]]


- Geef het gemiddelde, modus, mediaan en de standaarddeviatie van z


In [45]:
from scipy import stats

# Average
z_average = np.average(z)

# Mode
z_mode = stats.mode(z, axis=None)

# Standard deviation
z_std = np.std(z)

print(z_average)
print(z_mode)
print(z_std)

3.75
ModeResult(mode=np.int64(0), count=np.int64(2))
2.9755951785595207


<a id="np_opdracht2"></a>
## Opdracht 2
**Python list vs. NumPy**

- Maak een list `lst` met 1.000.001 willekeurige getallen tussen 0 en 10 (gebruik `random.randint(0, 10)`)
- Bepaal de mediaan
- Maak een list met daarin het kwadraat van elk element in `lst`
- Maak een list met daarin alleen alle even getallen uit `lst`
- Maak een tweede list `lst2` met 1.000.001 willekeurige getallen
- Maak een list met daarin de som van de elementen uit `lst` en `lst2`, dus:
  - `lst_samen[0] = lst[0] + lst2[0]`,
  - `lst_samen[1] = lst[1] + lst2[1]`,
  - etc.

- Doe bovenstaande ook met Numpy

- Gebruik `%timeit` voor je code om de snelheid te vergelijken

In [46]:
import math
import random
import timeit
import numpy as np

In [47]:
# Not numpy
def time_not_numpy():
    lst = [random.randint(0, 10) for i in range(0, 1000001)]
    median = np.median(lst)
    lst_kwadraat = [i ** 2 for i in lst]
    lst_even = [i for i in lst if i % 2 == 0]
    lst2 = [random.randint(0, 10) for i in range(0, 1000001)]
    lst_som = [lst[i] + lst2[i] for i in range(len(lst))]

# NumPy
def time_numpy():
    np_lst = np.random.randint(0, 11, size=1000001)
    np_median = np.median(np_lst)
    np_lst_kwadraat = np.square(np_lst)
    np_lst_even = np_lst[np_lst % 2 == 0]  # Gebruik een true of false mask. lst[lst % 2 == 0]
    np_lst2 = np.random.randint(0, 11, size=1000001)
    np_lst_som = np_lst + np_lst2

%timeit time_not_numpy()
%timeit time_numpy()


1.62 s ± 18.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
33.2 ms ± 324 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


<a id="np_opdracht3"></a>
## Opdracht 3

De blokcoördinator D.O. Cent van blok A  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [48]:
import numpy as np

Start met de data verzamelen:
- Lees tekstbestand: blokAcijfers.txt in met `np.loadtxt`, sla de data op in een numpy array met naam `vCijfers`.
- Laat zien dat de gegevens goed ingelezen zijn.
- Toon de array attributen.

In [49]:
vCijfers = np.loadtxt("blokAcijfers.txt")


def print_attributes(np_array):
    print(f"Dimensions: {np_array.ndim}")
    print(f"Size: {np_array.size}")
    print(f"Data type: {np_array.dtype}")
    print(f"Shape: {np_array.shape}")
    print(f"Bit size of items: {np_array.itemsize}")
    print(f"Memory: {np_array.data}")


print_attributes(vCijfers)


Dimensions: 2
Size: 30
Data type: float64
Shape: (10, 3)
Bit size of items: 8
Memory: <memory at 0x000001F42B2E6740>


De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [50]:
print(vCijfers[2,1])
print(vCijfers[9,0])

vCijfers[2,1] = 4.3
vCijfers[9,0] = 4.8

print(vCijfers[2,1])
print(vCijfers[9,0])

4.0
5.0
4.3
4.8


De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

In [51]:
import pandas

# Full array
print(np.min(vCijfers))
print(np.max(vCijfers))
print(np.average(vCijfers))
print()

# Per subject
subject_headers_columns = ["Vak1", "Vak2", "Vak3"]
subject_headers_rows = ["minimum", "maximum", "average"]
subject_data = [[np.min(vCijfers[:, 0]), np.min(vCijfers[:, 1]), np.min(vCijfers[:, 2])], 
                [np.max(vCijfers[:, 0]), np.max(vCijfers[:, 1]), np.max(vCijfers[:, 2])],
                [np.average(vCijfers[:, 0]), np.average(vCijfers[:, 1]), np.average(vCijfers[:, 2])]]
print(pandas.DataFrame(subject_data, subject_headers_rows, subject_headers_columns))

# Per student
student_headers_columns = ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10"]
student_headers_rows = ["minimum", "maximum", "average"]
student_data = [[np.min(vCijfers[0, :]), np.min(vCijfers[1, :]), np.min(vCijfers[2, :]), np.min(vCijfers[3, :]), np.min(vCijfers[4, :]), np.min(vCijfers[5, :]), np.min(vCijfers[6, :]), np.min(vCijfers[7, :]), np.min(vCijfers[8, :]), np.min(vCijfers[9, :])], 
                [np.max(vCijfers[0, :]), np.max(vCijfers[1, :]), np.max(vCijfers[2, :]), np.max(vCijfers[3, :]), np.max(vCijfers[4, :]), np.max(vCijfers[5, :]), np.max(vCijfers[6, :]), np.max(vCijfers[7, :]), np.max(vCijfers[8, :]), np.max(vCijfers[9, :])],
                [np.average(vCijfers[0, :]), np.average(vCijfers[1, :]), np.average(vCijfers[2, :]), np.average(vCijfers[3, :]), np.average(vCijfers[4, :]), np.average(vCijfers[5, :]), np.average(vCijfers[6, :]), np.average(vCijfers[7, :]), np.average(vCijfers[8, :]), np.average(vCijfers[9, :])]]
print(pandas.DataFrame(student_data, student_headers_rows, student_headers_columns))


3.2
9.0
6.653333333333333

         Vak1  Vak2  Vak3
minimum  3.20  4.30  3.50
maximum  8.60  8.00  9.00
average  6.21  6.89  6.86
               S1        S2        S3        S4   S5        S6        S7  \
minimum  6.400000  8.000000  3.200000  3.500000  7.3  8.000000  4.000000   
maximum  7.300000  8.500000  5.000000  7.900000  8.0  9.000000  6.000000   
average  6.733333  8.166667  4.166667  6.166667  7.7  8.533333  5.166667   

               S8        S9       S10  
minimum  7.300000  4.500000  4.800000  
maximum  7.800000  7.700000  7.200000  
average  7.633333  5.933333  6.333333  


De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [52]:
vCijfers_rounded = vCijfers.copy()
vCijfers_rounded = np.round(vCijfers_rounded)

print(vCijfers)
print(vCijfers_rounded)

[[6.5 7.3 6.4]
 [8.  8.  8.5]
 [3.2 4.3 5. ]
 [7.9 7.1 3.5]
 [7.3 7.8 8. ]
 [8.6 8.  9. ]
 [4.  6.  5.5]
 [7.3 7.8 7.8]
 [4.5 5.6 7.7]
 [4.8 7.  7.2]]
[[6. 7. 6.]
 [8. 8. 8.]
 [3. 4. 5.]
 [8. 7. 4.]
 [7. 8. 8.]
 [9. 8. 9.]
 [4. 6. 6.]
 [7. 8. 8.]
 [4. 6. 8.]
 [5. 7. 7.]]


Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [53]:
ophoogarray = np.zeros(vCijfers.shape)
ophoogarray[:, 0] = 0.5
vCijfers += ophoogarray
print(vCijfers)

[[7.  7.3 6.4]
 [8.5 8.  8.5]
 [3.7 4.3 5. ]
 [8.4 7.1 3.5]
 [7.8 7.8 8. ]
 [9.1 8.  9. ]
 [4.5 6.  5.5]
 [7.8 7.8 7.8]
 [5.  5.6 7.7]
 [5.3 7.  7.2]]


De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

In [54]:
voldoende_lijst = (vCijfers > 5.5)
print(voldoende_lijst)

[[ True  True  True]
 [ True  True  True]
 [False False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [False  True False]
 [ True  True  True]
 [False  True  True]
 [False  True  True]]


<a id="np_opdracht4"></a>
## Opdracht 4
**Deze opdracht is facultatief**

In [55]:
import numpy as np

#### 3. Create a null vector of size 10

In [56]:
vector1 = np.zeros((10))
print(vector1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [57]:
vector2 = np.zeros((10))
vector2[4] = 1
print(vector2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 8.  Reverse a vector with values ranging from 10 to 49 (first element becomes last)

In [58]:
vector3 = np.arange(10, 50)
vector3 = np.flip(vector3)
print(vector3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [59]:
vector4 = np.random.randint(0, 9, (3, 3))
print(vector4)

[[4 5 5]
 [3 1 4]
 [2 0 1]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [60]:
vector5 = np.array([1,2,0,0,4,0])
print(np.argwhere(vector5 > 0))

[[0]
 [1]
 [4]]


#### 11. Create a 3x3 identity matrix

In [61]:
vector6 = np.eye(3, 3)
print(vector6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [62]:
vector7 = np.random.randint(0, 10, (10, 10))
print(np.min(vector7))
print(np.max(vector7))

0
9


#### 15. Create a 2d array with 1 on the border and 0 inside

In [63]:
def ones_border(shape):
    vector8 = np.ones(shape)
    vector8[1:-1, 1:-1] = 0
    return vector8

print(ones_border((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [64]:
def checkboard():
    tile = [[0, 1], [1, 0]]
    vector9 = np.tile(tile, (4,4))
    return vector9

board = checkboard()
print(board)
print()
print(board.shape)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

(8, 8)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [71]:
vector10 = np.random.randint(0, 10, (20))
vector10[(vector10 < 8) & (vector10 > 3)] *= -1
print(vector10)

[ 2  2  2 -4  2  1  0 -6  2 -7  3 -5  3  2  0  8 -7  8 -6  0]


#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 36. Extract the integer part of a random array using 5 different methods

In [135]:
Z = np.random.uniform(0,10,10)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 42. Consider two random array A and B, check if they are equal

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 50. How to find the closest value (to a given scalar) in a vector?

In [136]:
v = np.random.uniform(0,100)

#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [137]:
Z = np.random.random((10,2))


#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

In [138]:
Z = np.random.uniform(0,1,10)
z = 0.5

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 72. How to swap two rows of an array?

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 83. How to find the most frequent value in an array?

#### 89. How to get the n largest values of an array