## Introductie NumPy

### Doel van  NumPy
Efficiënt grote verzamelingen nummerieke gegevens (arrays) verwerken. Veel efficiënter dan dat jezelf via for / while lussen kunt doen

In [1]:
# gebruik library
import numpy as np

In [2]:
# Gebruik np.<TAB><TAB> voor documentatie

### Aanmaken NumPy Arrays

In [3]:
# aanmaken van Arrays
# uit een Python List
np1 = np.array([1,4,2,5,3])
print(np1)

[1 4 2 5 3]


In [4]:
# uit een range definitie
np2 = np.arange(0,20,2)  # van 0 tot 20 per 2
np2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# meerdere dimensions random gevuld
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1); print(x2); print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


### Slicing (deel van array bepalen)

In [6]:
x = np.array(([5, 10, 15], [4, 14, 24], [3, 11, 19]))
x

array([[ 5, 10, 15],
       [ 4, 14, 24],
       [ 3, 11, 19]])

In [7]:
x[:,1] # alle rijen, 2e kolom

array([10, 14, 11])

In [8]:
x[1,:] # tweede rij, alle kolommen


array([ 4, 14, 24])

In [9]:
x[:2,1:]  # 1e en 2e rij, vanaf 2e kolom

array([[10, 15],
       [14, 24]])

### Berekeningen

In [10]:
x = np.array(([10,20,30], [40,50,60]))
y = np.array(([1,2,3], [4,5,6]))
print(x); print(y)

[[10 20 30]
 [40 50 60]]
[[1 2 3]
 [4 5 6]]


In [11]:
# Vergelijking tussen 2 arrays
print(x>y)

[[ True  True  True]
 [ True  True  True]]


In [12]:
# Berekenen met 'enkel' getal
print(x*2)

[[ 20  40  60]
 [ 80 100 120]]


In [13]:
# UFunc: universele functies op alle elemementen
print(np.multiply(x,2))

[[ 20  40  60]
 [ 80 100 120]]


In [14]:
# Aggregatie functies
print(np.min(x))

10


In [15]:
print(np.sum(x))

210


### Fancy indexing


In [16]:
z = np.array(([15,20,35], [45,50,55]))
x<z

array([[ True, False,  True],
       [ True, False, False]])

In [17]:
x[x<z]

array([10, 30, 40])

In [18]:
# Einde